### ISSUE TITLE
Compiling on OSX for Maya 2014

### ISSUE THREAD

**Issue by jmaruska** [Esri/esri-cityengine-sdk#18]
Has any one gotten this to work successfully? I keep getting:

Could not find a package configuration file provided by "prt4maya_codec"
  with any of the following names:

    prt4maya_codecConfig.cmake
    prt4maya_codec-config.cmake

It seems like it can't compile the encoder properly. Not sure if it's me or not...

**Comment by mistafunk** [comment]
i hope this has been resolved in the meantime, else please reopen.

**Comment by jmaruska** [comment]
nope. I never got it to work. Has anyone else reported success compiling on OS X?
