### ISSUE TITLE
Error generating mResolveMap with example Unity Plugin

### ISSUE THREAD

**Issue by rogerlew** [Esri/esri-cityengine-sdk#19]
Hi,

I've managed to compile the example unity plugin using VS2010 and Boost 1.53.0. I'm using CityEngine 2014.1, the esri_ce_sdk_1_2_1591_win32_vc10_rel_opt SDK, and Unity 4.5.2f1 Pro. The plugin loads fine, and the Custom Editor is also working just fine. In CityEngine I've shared the scifi_city.cga as scifi_city.rpk and placed it in my Assets folder.

When the rulepackage filename was specified Unity would crash. Debugging revealed that inside Context::setRulePackage (in Context.cpp) unpackPath was getting set to garbage by the mRulesFiles.clear() and SafeDestroy(mResolveMap) calls. 

When mResolveMap = prt::createResolveMap(url.c_str(), unpackPath, &status) was called it would result in an unhandled exception.

![cepluginbomb](https://cloud.githubusercontent.com/assets/3652906/4485245/c2e924e2-49c7-11e4-8f7b-1f729606a842.png)

In a followup attempt I commented out mRulesFiles.clear() and SafeDestroy(mResolveMap), rebuilt the plugin, and reattempted to run the plugin from Unity. When creating the resolve map the input arguments look correct but it fails with an unspecified error. I've also tried the candler.rpk with the same result.

![cepluginsmallexplosion](https://cloud.githubusercontent.com/assets/3652906/4485293/b05a5bec-49c8-11e4-8314-ce3cbfcf6626.png)

I have a feeling it is close to working, but I'm at a loss of what to check for. Some guidance here would be be greatly appreciated.

**Comment by mistafunk** [comment]
apologies - we missed your question. is this still an issue?

**Comment by zsunpl** [comment]
I have encounter the same problem, and did't know how to solve.Please help...

**Comment by mistafunk** [comment]
i hope this has been resolved in the meantime, else please try with the latest release and/or reopen the ticket.
