### ISSUE TITLE
Unity: Unable to locate com.esri.prt.examples.UnityEncoder

### ISSUE THREAD

**Issue by bilke** [Esri/esri-cityengine-sdk#21]
I compiled everything fine on Windows and installed the dlls in the Unity (4.6) application folder. Now when I start Unity and also when I press the `Generate`-button on the `Prt4Unity`-script I get the following error popup:

```
Unable to locate com.esri.prt.examples.UnityEncoder
```

In the Unity console the following errors appear:

```
[2015-Jun-16 12:06:03.690683] [error] prt::createEncoderInfo failed, exception caught: 'Encoder not found.'
UnityEngine.Debug:LogError(Object)
Prt4Unity:LogMessage(String, Int32) (at Assets/Prt4Unity/Scripts/Prt4Unity.cs:547)
Prt4Unity:CreateContext()
Context:.ctor() (at Assets/Prt4Unity/Scripts/Prt4Unity.cs:148)
Prt4Unity:.ctor() (at Assets/Prt4Unity/Scripts/Prt4Unity.cs:449)
UnityEditor.HostView:OnGUI()

[2015-Jun-16 12:06:03.712684] [error] Status code = 18 = Encoder not found.
UnityEngine.Debug:LogError(Object)
Prt4Unity:LogMessage(String, Int32) (at Assets/Prt4Unity/Scripts/Prt4Unity.cs:547)
Prt4Unity:CreateContext()
Context:.ctor() (at Assets/Prt4Unity/Scripts/Prt4Unity.cs:148)
Prt4Unity:.ctor() (at Assets/Prt4Unity/Scripts/Prt4Unity.cs:449)
UnityEditor.HostView:OnGUI()
```

**Comment by mistafunk** [comment]
please note we only tested the unity example with Unity 4.3. we hope to update the example to unity 5 soon...

**Comment by bilke** [comment]
Unity 4.3 is almost two years old... I suggest you remove the listed Unity feature (under *CityEngine SDK* on the [CityEngine feature page](http://www.esri.com/software/cityengine/features)) until you provide a working version. Otherwise paying customers may not be amused...

**Comment by mistafunk** [comment]
there seems to be a misunderstanding. the feature page states:

"The CityEngine SDK **allows you** to embed procedural geometry creation in other applications such as [...], game engines (e.g. Unity3D, Unreal Engine), [...]."

we do not provide the actual unity plugin as a product ourselves at this point. the example code in this repo is just a template to get our customer started. we are very happy to receive pull requests (e.g. to get it to work with unity 5).
