### ISSUE TITLE
Issue with building unity pluging

### ISSUE THREAD

**Issue by KaiFlorian** [Esri/esri-cityengine-sdk#24]
Hello,

I am trying to build the example unity plugin in visual studio 2010 sp1. However, it seems that the header files cannot be found or opened. I am using CityEngine 2014.0. I would appreciate if someone let me know how I can resolve this.

Thanks,
Kai

![capture](https://cloud.githubusercontent.com/assets/13235297/9431367/f5fd372e-4a52-11e5-99de-fe87a38ba43f.JPG)

**Comment by matthias-specht** [comment]
Hi Kai,
looks like the include path to prt is wrong. Can you verify that in the project settings?

**Comment by KaiFlorian** [comment]
Hi Matthias. I have set the include path for prt and prtx. However, I still get the two errors saying that error LNK1104: cannot open file 'com.esri.prt.core.lib'	


I tried to resolve this by defining the full path to this library (which is in .....\prt\bin folder) for both projects through Configuration Properties--> Linker--> Input--> Additional Dependencies
After doing this, I got another errors saying that 
error LNK1112: module machine type 'X86' conflicts with target machine type 'x64'	

Is this project for 32bit windows? My OS is Win64.

Thanks

![capture](https://cloud.githubusercontent.com/assets/13235297/9486467/d47f1054-4c0a-11e5-8d98-43f78e1a9443.JPG)

**Comment by matthias-specht** [comment]
Hi Kai,
yes, the Unity example is for 32bit only. you need to download the 32bit build (suffix ...-win32-vc100-x86-rel-opt.zip).

greetings
Matthias

**Comment by misspawty** [comment]
Hello, 

In continuance to this discussion, i would like to ask if the unity plug in is built for unity 4.3 only. 
I have succesfully built the plugin, but i am getting an error in unity saying that "this plugin is only supported in unity pro".  Do we need a pro licence for this?

Thank you, 

F.

**Comment by musenlinc** [comment]
Hi Matthias, 
sorry to ask about this one year later, I'm also trying this example. thanks to your answer I succeed on building solution (Configuration: Release) as shown in picture, but "prt4unity" can't be debug as picture2. I ran deploy.cmd, but the two new directories are empty.
![uc 20161011160318](https://cloud.githubusercontent.com/assets/22762467/19262065/da737874-8fcf-11e6-95ff-86f25451ad65.png)
![uc 20161011160203](https://cloud.githubusercontent.com/assets/22762467/19262080/efdf7d52-8fcf-11e6-83b6-0ab7d984ccdd.png)

 i cannot complete and i think i might fail on build solution or installation step1. Could you mind giving me some advice? 
Thanks for your work,
CHEN

**Comment by kmbawuazo** [comment]
LINK OF THE CityEngine 2014 PLEASE !!   bobelmagno@gmail.com
