### ISSUE TITLE
How to call generate for each initial shape in parallel?

### ISSUE THREAD

**Issue by c00284934** [Esri/esri-cityengine-sdk#25]
Dear experts, if the "numberWorkerThreads" can not  generate initial shapes in parallel, then how to achieve it.  Could you give me some tips on how to use the cityengine  sdk to  call generate for each initial shape in parallel ?  
Looking forward to your reply.

**Comment by mistafunk** [comment]
hi,

just call the [generate function](http://esri.github.io/esri-cityengine-sdk/html/namespaceprt.html#a0ea77f812e862aa5e15b1234220fd368) for each initial shape in parallel.

best,
simon

**Comment by c00284934** [comment]
Thank you! Do you mean that I should call the  generate function for each initial shape by  multiple threads ?

**Comment by mistafunk** [comment]
yes, this is supported. make sure that the callback implementation you are using for the parallel generate calls is thread safe.

best,
simon

**Comment by c00284934** [comment]
OK,thank you!
