### ISSUE TITLE
Unity Plugin, unity3d 4.3.4

### ISSUE THREAD

**Issue by musenlinc** [Esri/esri-cityengine-sdk#28]
Hi Matthias, 
sorry to ask about this one year later, I'm also trying this example. thanks to your answer I succeed on building solution (Configuration: Release) as shown in picture, but "prt4unity" can't be debug as picture2. I ran deploy.cmd, but the two new directories are empty.
![uc 20161011160318](https://cloud.githubusercontent.com/assets/22762467/19262065/da737874-8fcf-11e6-95ff-86f25451ad65.png)
![uc 20161011160203](https://cloud.githubusercontent.com/assets/22762467/19262080/efdf7d52-8fcf-11e6-83b6-0ab7d984ccdd.png)

 i cannot complete and i think i might fail on build solution or installation step1. Could you mind giving me some advice? 
Thanks for your work,
CHEN

**Comment by matthias-specht** [comment]
Hi Chen,
sorry but the Unity example has been deprecated.
