### ISSUE TITLE
Using this ce_sdk in Win10_Unityx64

### ISSUE THREAD

**Issue by PaPeaRL** [Esri/esri-cityengine-sdk#31]
Hi mistafunk
   I'm a user of city engine who want to generate building in Unity SDK. I can't export my model to fbx because my building model include too much area (I think this is the reason but not sure). I try to use your repo to import CityEngine SDK in my Unity but I have some problem.
  - My Visual studio is 2017 version (prt4unity required 2010), I re-target project and change platform tool-set  to v141 (VS 2017 support)
  - My CityEngine and Unity is x64, I'm not sure but I think your repo created for x84 user isn't it? When I run deploy.cmd I found two directories in top-level of repo. that is  "ProgramFiles(x86)\Unity\Editor" and "MyUnityProject\Asset\Plugins|Prt4Unity\..." but all folder didn't have any file.

I'm not sure what is my mistake about this solution but I think I follow your Read me document, please recommended how can I fix this mistake.

Thank you in advance

**Comment by mistafunk** [comment]
hi PaPeaRL,

unfortunately, the prt4unity example is deprecated and we do not support it anymore. the only way forward is to upgrade the example code to a current unity version. additionally, i doubt that you can circumvent size issues encountered with FBX by generating the model inside unity. we are still hoping to resurrect support for the unity example in the future.

apologies for the mixed news & kind regards,
simon
